[pytest]
# pytest配置文件

# 测试文件匹配规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 测试目录
testpaths = testcases

# 详细输出
addopts = -v -s --tb=short --alluredir report

# 日志配置
log_cli = true
log_cli_level = INFO
